os:
  - linux

# Tells Travis we're running on a Node environment
language: 'node_js'
node_js: '12'

# https://docs.travis-ci.com/user/caching/#yarn-cache
cache: yarn

script:
  - yarn test
  - yarn buildpackage
