
name: Test

on: [push]

jobs:
  buildNPublish:
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: yarn
      - run: yarn test
      - run: yarn buildpackage
